name: Build and Deploy
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compress HTML
        run: |
          npm install -g html-minifier
          html-minifier --collapse-whitespace --remove-comments --minify-css true --minify-js true index.html -o index.html
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: .
